service: django

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.7
  layers:
    - !Ref InternalPythonExtensionDjangoExampleLambdaLayer
    # - !Ref ExternalAgnosticExtensionDjangoExampleLambdaLayer
  environment:
    OTEL_RESOURCE_ATTRIBUTES: custom.name=example-project,custom.tag.provider=serverless,service.name=service
    OTEL_PYTHON_LOG_LEVEL: debug
    OTEL_PYTHON_LOG_CORRELATION: true
    SLS_OTEL_USER_SETTINGS: |
      {
          "common": {
              "http": {
                  "request": {
                      "headers": [
                          {
                              "serverless_token": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                          }
                      ]
                  }
              }
          },
          "extension": {
              "opentelemetry": {
                  "http": {
                    "url": "http://webhook.site/9fe27a37-8ebd-4a3b-9969-e446cfb03951"
                  }
              },
              "logs": {
                  "http": {
                    "url": "http://localhost:4269"
                  }
              }
          },
          "opentelemetry": {
              "resource": {
                  "attributes": {
                      "service.name": "${self:service}",
                      "sls_service_name": "${self:service}",
                      "sls_stage": "${sls.stage}",
                      "sls_org_id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
                  }
              }
          },
          "logs": {
              "http": {
                  "request": {
                      "url": "https://webhook.site/9fe27a37-8ebd-4a3b-9969-e446cfb03951/ingestion/kinesis/v1/logs"
                  }
              }
          },
          "metrics": {
              "http": {
                  "request": {
                      "url": "https://webhook.site/9fe27a37-8ebd-4a3b-9969-e446cfb03951/ingestion/kinesis/v1/metrics"
                  }
              }
          },
          "request": {
              "http": {
                  "request": {
                      "url": "https://webhook.site/9fe27a37-8ebd-4a3b-9969-e446cfb03951/ingestion/kinesis/v1/request-response"
                  }
              }
          },
          "response": {
              "http": {
                  "request": {
                      "url": "https://webhook.site/9fe27a37-8ebd-4a3b-9969-e446cfb03951/ingestion/kinesis/v1/request-response"
                  }
              }
          },
          "traces": {
              "http": {
                  "request": {
                      "url": "https://webhook.site/9fe27a37-8ebd-4a3b-9969-e446cfb03951/ingestion/kinesis/v1/traces"
                  }
              }
          }
      }

package:
  patterns:
    - "!**"
    - "handler.py"
    - "manage.py"
    - "wsgi_handler.py"
    - "serverless_wsgi.py"
    - ".serverless_wsgi"
    - "project/**"
    - "pages/**"

functions:
  api:
    handler: serverless_aws_lambda_otel_extension_internal.wrapper.auto_instrumenting_handler
    #handler: handler.hello
    environment:
      ORIG_HANDLER: wsgi_handler.handler
      DJANGO_SETTINGS_MODULE: project.settings
      STRIP_STAGE_PATH: true
    events:
      - httpApi: ANY /
      - httpApi: ANY /nested/{param}

plugins:
  - serverless-python-requirements

layers:
  # externalAgnosticExtensionDjangoExample:
  #   package:
  #     artifact: ../../../../../node/packages/aws-lambda-otel-extension/dist/extension-external.zip
  internalPythonExtensionDjangoExample:
    path: ../../assets/internal
    package:
      patterns:
        - "!**"
        - "otel-extension-internal-python/*"
