[build-system]
requires = ["setuptools>=65.6.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "serverless-sdk"
version = "0.0.1"
description = "Serverless SDK for Python"
authors = [{ name = "serverlessinc" }]
dependencies = [
  "typing-extensions>=4.4.0"
]

requires-python = ">=3.7"
