# Output payloads can be seen at https://webhook.site/#!/7e7e19a5-e875-462d-b5b8-6c46df0d2a98

service: serverless-console-python-example

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  layers:
    - !Ref InternalPythonExtensionLambdaLayer
    - !Ref ExternalAgnosticExtensionLambdaLayer
  environment:
    AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-extension-internal-python/exec-wrapper.sh
    SLS_OTEL_SERVER_URL: http://webhook.site/9fe27a37-8ebd-4a3b-9969-e446cfb03951
    SLS_OTEL_RESOURCE_ATTRIBUTES: 'sls_service_name=${self:service},sls_stage=${sls:stage},sls_org_id=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
    OTEL_RESOURCE_ATTRIBUTES: 'custom.name=example-project,custom.tag.provider=serverless'
    SLS_OTEL_USER_SETTINGS: '{
      "common": {
        "destination": {
          "requestHeaders": "serverless_token=7e492185-581c-4444-a86a-f162d372e398"
        }
      },
      "logs": {
        "destination": "https://webhook.site/9fe27a37-8ebd-4a3b-9969-e446cfb03951/ingestion/kinesis/v1/logs"
      },
      "metrics": {
        "destination": "https://webhook.site/9fe27a37-8ebd-4a3b-9969-e446cfb03951/ingestion/kinesis/v1/metrics"
      },
      "request": {
        "destination": "https://webhook.site/9fe27a37-8ebd-4a3b-9969-e446cfb03951/ingestion/kinesis/v1/request-response"
      },
      "response": {
        "destination": "https://webhook.site/9fe27a37-8ebd-4a3b-9969-e446cfb03951/ingestion/kinesis/v1/request-response"
      },
      "traces": {
        "destination": "https://webhook.site/9fe27a37-8ebd-4a3b-9969-e446cfb03951/ingestion/kinesis/v1/traces"
      }
    }'


package:
  patterns:
    - "!**"
    - "handler.py"

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi: '*'
  helloLocal:
    handler: serverless.aws_lambda_otel_extension.internal.wrapper.auto_instrumenting_handler
    environment:
      ORIG_HANDLER: handler.hello

plugins:
  - serverless-python-requirements

layers:
  externalAgnosticExtension:
    package:
      artifact: ../../../../node/packages/aws-lambda-otel-extension/dist/extension-external.zip
  internalPythonExtension:
    package:
      artifact: ../dist/extension.zip
