[build-system]
requires = [
    "setuptools>=65.6.3",
    "wheel",
    "betterproto[compiler]>=2.0.0b5,<3.0.0", # This version supports proto3 optional fields
    "grpcio-tools>=1.51.1,<2.0.0",
    "poethepoet>=0.17.1,<1.0.0",
    "protobuf >= 4.21.12",
]
build-backend = "setuptools.build_meta"

[project]
name = "serverless-sdk-schema"
version = "0.0.1"
description = "The protobuf generated Serverless SDK Schema"
authors = [{ name = "serverlessinc" }]
dependencies = [
    "protobuf >= 4.21.12",
    "typing-extensions>=4.4.0", # included in Python 3.8 - 3.11
]

requires-python = ">=3.7"


[project.optional-dependencies]
tests = [
    "pytest>=7.2.0",
    "black>=22.12.0",
    "ruff>=0.0.199",
]


[tool.ruff]
ignore = ["F401"]


[tool.poe.tasks]
build = "bash ./scripts/build.sh"
install = "bash ./scripts/install.sh"
test = "python3 -m pytest"
