name: "Python: Validate"

on:
  pull_request:
    branches: [main]
    paths:
      - python/**
      - proto/**

jobs:
  linuxPython37:
    name: "[Linux] Python 3.7: Lint, Formatting & Unit Tests"
    runs-on: ubuntu-latest
    steps:

